spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/zhanglfdatabase?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
